default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  application_name: synaxis_koinonia
  schema_search_path: sch_synaxis_koinonia, public
  host: <%= ENV["DEFAULT_DATABASE_HOST"] %>
  database: <%= ENV["DEFAULT_DATABASE_NAME"] %>
  username: <%= ENV["DEFAULT_DATABASE_USERNAME"] %>
  password: <%= ENV["DEFAULT_DATABASE_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DATABASE_NAME") { "#{ENV['DEFAULT_DATABASE_NAME']}_test" } %>

production:
  <<: *default
